import { v } from "convex/values";
import { query } from "./_generated/server";
import { requireMembership } from "./lib/auth";

export const getWorkspace = query({
  args: {
    organizationId: v.id("organizations"),
  },
  handler: async (ctx, args) => {
    await requireMembership(ctx, args.organizationId);
    const organization = await ctx.db.get(args.organizationId);
    if (!organization) return null;

    const [
      memberships,
      customers,
      contacts,
      properties,
      propertyAreas,
      leads,
      opportunities,
      estimates,
      approvalRequests,
      invoices,
      payments,
      serviceCatalog,
      servicePackages,
      priceBookItems,
      pricingRules,
      crews,
      jobs,
      jobPhases,
      visits,
      recurringServicePlans,
      changeOrders,
      tasks,
      activities,
      notes,
      files,
      materials,
    ] = await Promise.all([
      ctx.db.query("memberships").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("customers").withIndex("by_org_updated", (q) => q.eq("organizationId", args.organizationId)).order("desc").collect(),
      ctx.db.query("contacts").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("properties").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("propertyAreas").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("leads").withIndex("by_org_created", (q) => q.eq("organizationId", args.organizationId)).order("desc").collect(),
      ctx.db.query("opportunities").withIndex("by_org_updated", (q) => q.eq("organizationId", args.organizationId)).order("desc").collect(),
      ctx.db.query("estimates").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("approvalRequests").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("customerInvoices").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("customerPayments").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("serviceCatalogItems").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("servicePackages").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("priceBookItems").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("pricingRules").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("crews").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("jobs").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("jobPhases").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("jobVisits").withIndex("by_org_date", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("recurringServicePlans").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("changeOrders").withIndex("by_org_updated", (q) => q.eq("organizationId", args.organizationId)).order("desc").collect(),
      ctx.db.query("tasks").withIndex("by_org_due", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("activities").withIndex("by_org_time", (q) => q.eq("organizationId", args.organizationId)).order("desc").collect(),
      ctx.db.query("notes").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("files").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
      ctx.db.query("materials").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).collect(),
    ]);

    const users = await Promise.all(memberships.map((membership) => ctx.db.get(membership.userId)));
    const primaryContactByCustomer = new Map(contacts.filter((contact) => contact.isPrimary).map((contact) => [contact.customerId, contact]));

    return {
      organization: {
        id: organization._id,
        name: organization.name,
        timezone: organization.timezone,
      },
      members: memberships.map((membership, index) => {
        const user = users[index];
        return {
          id: user?._id ?? membership.userId,
          name: user?.name ?? "Unknown member",
          email: user?.email ?? "",
          role: membership.role,
        };
      }),
      customers: customers.map((customer) => {
        const contact = primaryContactByCustomer.get(customer._id);
        return {
          id: customer._id,
          name: customer.name,
          type: customer.type,
          status: customer.status === "do_not_service" ? "inactive" : customer.status,
          phone: contact?.phone ?? contact?.mobilePhone ?? "",
          email: contact?.email ?? "",
          tags: customer.tags,
          ownerId: customer.ownerUserId ?? "",
        };
      }),
      contacts: contacts.map((contact) => ({
        id: contact._id,
        customerId: contact.customerId,
        name: contact.name,
        email: contact.email,
        phone: contact.phone ?? contact.mobilePhone,
        roleTitle: contact.roleTitle,
        isPrimary: contact.isPrimary ?? false,
      })),
      properties: properties.map((property) => ({
        id: property._id,
        customerId: property.customerId,
        label: property.label,
        street: property.street,
        city: property.city,
        state: property.state,
        postalCode: property.postalCode,
        notes: property.notes ?? "",
        lawnSizeSqFt: property.lawnSizeSqFt,
      })),
      propertyAreas: propertyAreas.map((area) => ({
        id: area._id,
        propertyId: area.propertyId,
        name: area.name,
        kind: area.kind,
        size: area.size,
        unit: area.unit,
        notes: area.notes,
      })),
      leads: leads.map((lead) => ({
        id: lead._id,
        title: lead.title,
        customerId: lead.customerId ?? "",
        propertyId: lead.propertyId ?? "",
        source: lead.source,
        status: lead.status === "do_estimate" || lead.status === "estimate_provided" || lead.status === "follow_up" || lead.status === "waiting" ? "contacted" : lead.status === "spam" ? "disqualified" : lead.status === "lost_confirmed" || lead.status === "lost_assumed" || lead.status === "passed_on" || lead.status === "unqualified" ? "disqualified" : lead.status,
        urgency: lead.urgency,
        ownerId: lead.ownerUserId ?? "",
        leadType: lead.leadType,
        accountType: lead.accountType,
        companyAssignment: lead.companyAssignment,
        programRequests: lead.programRequests,
        lawnSizeSqFt: lead.lawnSizeSqFt,
        message: lead.message,
        estimateNotes: lead.estimateNotes,
        qualityScore: lead.qualityScore,
        spamScore: lead.spamScore,
        receivedAt: lead.receivedAt,
        createdAt: lead.createdAt,
      })),
      opportunities: opportunities.map((opportunity) => ({
        id: opportunity._id,
        leadId: opportunity.leadId,
        customerId: opportunity.customerId,
        propertyId: opportunity.propertyId ?? "",
        title: opportunity.title,
        stage: opportunity.stage,
        valueCents: opportunity.valueCents,
        closeProbability: opportunity.closeProbability,
        expectedCloseDate: opportunity.expectedCloseDate ?? opportunity.updatedAt,
        ownerId: opportunity.ownerUserId ?? "",
        serviceLines: opportunity.serviceLines,
        updatedAt: opportunity.updatedAt,
      })),
      estimates: estimates.map((estimate) => ({
        id: estimate._id,
        opportunityId: estimate.opportunityId ?? "",
        customerId: estimate.customerId,
        propertyId: estimate.propertyId ?? "",
        estimateNumber: estimate.estimateNumber,
        status: estimate.status,
        approvalStatus: estimate.approvalStatus,
        subtotalCents: estimate.subtotalCents,
        discountCents: estimate.discountCents,
        taxCents: estimate.taxCents,
        totalCents: estimate.totalCents,
        sentAt: estimate.sentAt,
        acceptedAt: estimate.acceptedAt,
        acceptedByName: estimate.acceptedByName,
        acceptedByEmail: estimate.acceptedByEmail,
        acceptanceSource: estimate.acceptanceSource,
        acceptanceNote: estimate.acceptanceNote,
        expiresAt: estimate.expiresAt,
        terms: estimate.terms,
      })),
      approvalRequests: approvalRequests.map((request) => {
        const estimate = estimates.find((candidate) => candidate._id === request.estimateId);
        const customer = customers.find((candidate) => candidate._id === request.customerId);
        return {
          id: request._id,
          estimateId: request.estimateId,
          estimateNumber: estimate?.estimateNumber ?? "Estimate",
          opportunityId: request.opportunityId,
          customerId: request.customerId,
          customerName: customer?.name ?? "Customer",
          requestedByUserId: request.requestedByUserId,
          assignedApproverUserId: request.assignedApproverUserId,
          status: request.status,
          reasonDetails: request.reasonDetails,
          riskScore: request.riskScore,
          grossMarginPercent: request.grossMarginPercent,
          discountCents: request.discountCents,
          discountPercent: request.discountPercent,
          estimatedCostCents: request.estimatedCostCents,
          totalCents: request.totalCents,
          dueAt: request.dueAt,
          requestedAt: request.requestedAt,
          decidedByUserId: request.decidedByUserId,
          decidedAt: request.decidedAt,
          decisionComment: request.decisionComment,
        };
      }),
      invoices: invoices.map((invoice) => ({
        id: invoice._id,
        customerId: invoice.customerId,
        jobId: invoice.jobId,
        estimateId: invoice.estimateId,
        invoiceNumber: invoice.invoiceNumber,
        status: invoice.status,
        subtotalCents: invoice.subtotalCents,
        taxCents: invoice.taxCents,
        totalCents: invoice.totalCents,
        paidCents: invoice.paidCents,
        dueAt: invoice.dueAt,
        sentAt: invoice.sentAt,
        paidAt: invoice.paidAt,
      })),
      payments: payments.map((payment) => ({
        id: payment._id,
        customerId: payment.customerId,
        invoiceId: payment.invoiceId,
        status: payment.status,
        method: payment.method,
        amountCents: payment.amountCents,
        receivedAt: payment.receivedAt,
        reference: payment.reference,
      })),
      serviceCatalog: serviceCatalog.map((item) => ({
        id: item._id,
        name: item.name,
        category: item.category,
        description: item.description,
        defaultUnit: item.defaultUnit,
        defaultPriceCents: item.defaultPriceCents,
        durationMinutes: item.durationMinutes,
        active: item.active,
      })),
      servicePackages: servicePackages.map((item) => ({
        id: item._id,
        name: item.name,
        category: item.category,
        description: item.description,
        includedServiceCatalogItemIds: item.includedServiceCatalogItemIds,
        defaultPriceCents: item.defaultPriceCents,
        billingCadence: item.billingCadence,
        laborHours: item.laborHours,
        laborRateCents: item.laborRateCents,
        materialCostCents: item.materialCostCents,
        equipmentCostCents: item.equipmentCostCents,
        overheadPercent: item.overheadPercent,
        targetMarginPercent: item.targetMarginPercent,
        checklistDefaults: item.checklistDefaults,
        active: item.active,
      })),
      priceBookItems: priceBookItems.map((item) => ({
        id: item._id,
        serviceCatalogItemId: item.serviceCatalogItemId,
        name: item.name,
        unit: item.unit,
        basePriceCents: item.basePriceCents,
        minPriceCents: item.minPriceCents,
        pricingModel: item.pricingModel,
        formula: item.formula,
        active: item.active,
      })),
      pricingRules: pricingRules.map((rule) => ({
        id: rule._id,
        priceBookItemId: rule.priceBookItemId,
        name: rule.name,
        condition: rule.condition,
        adjustmentType: rule.adjustmentType,
        adjustmentValue: rule.adjustmentValue,
        order: rule.order,
        active: rule.active,
      })),
      crews: crews.map((crew) => ({
        id: crew._id,
        name: crew.name,
        color: crew.color,
        active: crew.active,
      })),
      jobs: jobs.map((job) => ({
        id: job._id,
        customerId: job.customerId,
        propertyId: job.propertyId ?? "",
        opportunityId: job.opportunityId,
        estimateId: job.estimateId,
        title: job.title,
        status: job.status,
        priority: job.priority,
        managerId: job.managerUserId ?? "",
        startDate: job.startDate ?? job.createdAt,
        recurrence: job.recurrence,
      })),
      jobPhases: jobPhases.map((phase) => ({
        id: phase._id,
        jobId: phase.jobId,
        name: phase.name,
        status: phase.status,
        sortOrder: phase.sortOrder,
        startDate: phase.startDate,
        dueDate: phase.dueDate,
        completedAt: phase.completedAt,
      })),
      visits: visits.map((visit) => ({
        id: visit._id,
        jobId: visit.jobId,
        customerId: visit.customerId,
        propertyId: visit.propertyId ?? "",
        scheduledStart: visit.scheduledStart,
        scheduledEnd: visit.scheduledEnd,
        status: visit.status,
        routeOrder: visit.routeOrder ?? 0,
        crewId: visit.assignedCrewId ?? "",
        checklist: visit.checklist,
        notes: visit.notes ?? "",
      })),
      recurringServicePlans: recurringServicePlans.map((plan) => ({
        id: plan._id,
        customerId: plan.customerId,
        propertyId: plan.propertyId,
        jobId: plan.jobId,
        crewId: plan.crewId,
        name: plan.name,
        frequency: plan.frequency,
        intervalDays: plan.intervalDays,
        visitDurationMinutes: plan.visitDurationMinutes,
        nextRunAt: plan.nextRunAt,
        lastGeneratedAt: plan.lastGeneratedAt,
        generatedVisitIds: plan.generatedVisitIds,
        status: plan.status,
      })),
      changeOrders: changeOrders.map((changeOrder) => ({
        id: changeOrder._id,
        jobId: changeOrder.jobId,
        customerId: changeOrder.customerId,
        propertyId: changeOrder.propertyId,
        estimateId: changeOrder.estimateId,
        title: changeOrder.title,
        description: changeOrder.description,
        status: changeOrder.status,
        requestedByName: changeOrder.requestedByName,
        approvedByName: changeOrder.approvedByName,
        approvedByEmail: changeOrder.approvedByEmail,
        revenueDeltaCents: changeOrder.revenueDeltaCents,
        estimatedCostDeltaCents: changeOrder.estimatedCostDeltaCents,
        grossProfitDeltaCents: changeOrder.grossProfitDeltaCents,
        grossMarginPercent: changeOrder.grossMarginPercent,
        scheduleImpactDays: changeOrder.scheduleImpactDays,
        requestedAt: changeOrder.requestedAt,
        approvedAt: changeOrder.approvedAt,
        taskId: changeOrder.taskId,
      })),
      tasks: tasks.map((task) => ({
        id: task._id,
        entityType: task.entityType,
        entityId: task.entityId,
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        dueAt: task.dueAt ?? task.createdAt,
        assignedUserId: task.assignedUserId ?? "",
      })),
      activities: activities.map((activity) => ({
        id: activity._id,
        entityType: activity.entityType,
        entityId: activity.entityId,
        kind: activity.kind,
        summary: activity.summary,
        actorId: activity.actorUserId ?? "",
        occurredAt: activity.occurredAt,
      })),
      notes: notes.map((note) => ({
        id: note._id,
        entityType: note.entityType,
        entityId: note.entityId,
        body: note.body,
        visibility: note.visibility,
        createdByUserId: note.createdByUserId,
        createdAt: note.createdAt,
      })),
      files: files.map((file) => ({
        id: file._id,
        entityType: file.entityType,
        entityId: file.entityId,
        fileName: file.fileName,
        contentType: file.contentType,
        size: file.size,
        createdByUserId: file.createdByUserId,
        createdAt: file.createdAt,
      })),
      materials: materials.map((material) => ({
        id: material._id,
        name: material.name,
        unit: material.unit,
        costCents: material.costCents,
        epaRegistrationNumber: material.epaRegistrationNumber,
        restrictedUse: material.restrictedUse,
        active: material.active,
      })),
    };
  },
});
